### ISSUE TITLE
add better description to readme

### ISSUE THREAD

**Issue by stoeffel** [1-liners/1-liners#62]
Something better than

> Useful oneliners and shorthand functions

Check #34 for ideas.

I'm pretty bad with writing, would be nice to get some help from you guys. @hemanth @tomekwi

**Comment by tomekwi** [comment]
I hope I’ll have some time next week. Before that it’ll probably be hard.

**Comment by stoeffel** [comment]
No need to hurry. Thanks for your help :smile:

**Comment by stoeffel** [comment]
Add something like:

Why only one line? Because all functions from thia library should be as simple as possible. You should exactly know what they do and don't have to make any assumptions.

**Comment by tomekwi** [comment]
<sup><i>Made in Switzerland</i></sup>

1-liners
====

**Functional tools that couldn’t be simpler.**

We’re proud to present *1-liners* – a stupid-simple functional utility belt. 62 *[@stoeffel this can update automatically]* one-liner functions, hand-crafted with love and attention.

You get a product of top-quality functional programming craftmanship. Each function *[link to a function?]* follows the *KISS* principle, which we’ve broken down into ten concrete rules:

1. Each function shall **fit in one readable line of code**  
– so you can grasp it by just glimpsing at the source code.

2. Each function shall **have no side-effects**  
– so you can use it with confidence.

3. Each function shall **have a stable number of arguments**  
– so that it’s dead easy to bind, curry and uncurry.

4. Each function shall **deal with data in an immutable way**  
– so you can avoid debugging nightmares.

5. Each function shall **take data as the last argument**  
– *@stoeffel, it would be good to link to an article or something here*

6. Each function shall **be in a separate micro-module**  
– so that you download or load only what you need.

7. Each function shall **be thoroughly tested**  
– 100% code coverage guaranteed. We even test if every function fits in one line.

8. Each function shall **have great documentation**  
– the docs show usage and the source, and link to the specification.

9. We shall provide functional versions of **native object methods**  
– like `array.reduce`.

10. We shall provide functional versions of **language constructs**  
– like `+` or `&&`.

**Comment by tomekwi** [comment]
Two more thoughts to what I wrote:

1. The bold part can of every commandment can be a link to a function or the docs.
2. It would be good to grey out the “– you can…” part. I don’t know if GitHub allows it.

**Comment by stoeffel** [comment]
First off, I love it!!! It's great :100: :+1: 

> 62 [@stoeffel this can update automatically] 

nice

> deal with data in an immutable way

we have to check that.

>  [@stoeffel, it would be good to link to an article or something here]

I will search for one.

**Comment by tomekwi** [comment]
@stoeffel how do you like it when wrapped in a blockquote?

**Comment by tomekwi** [comment]
Or we could use an image to separate the decalogue visually. Could be in this style, if we go down the path of crafsmanship:

![](http://www.woodcarvingservices.co.uk/images/design_main.png)

Or do something more modern to better match the logo.

**Comment by stoeffel** [comment]
> blockquote

:+1:

I think using an image is maybe a little to much.

**Comment by tomekwi** [comment]
:+1:

I also used the name “decalogue” at first – hence the form of [commandments](https://en.wikipedia.org/wiki/Ten_Commandments) (“Each function shall…”). But it somehow flew out on the way. 

How about bringing the *decalogue* back in? Like “…which we’ve broken down into a small decalogue:” We could even go as far as “Each function shalt…” but perhaps it’s overkill.

Or just drop the analogy altogether and just make the thing simpler: “Each function fits in one readable line of code.”.

**Comment by stoeffel** [comment]
> “Thou shalt make each function fit in one readable line of code.” Fun or overkill?

Fun :smiley_cat:

**Comment by tomekwi** [comment]
@stoeffel you once asked me if I have a live, open-source example of using 1-liners. Well, now I have – however simple it is :) https://github.com/studio-b12/doxie-core/blob/62a19a2/module/index.js

**Comment by tomekwi** [comment]
Closed via #103
