### ISSUE TITLE
remove unstable badge when 1.0.0

### ISSUE THREAD

**Issue by stoeffel** [1-liners/1-liners#63]
^^

**Comment by tomekwi** [comment]
I just got a peculiar email:

>---------- Forwarded message ----------
> 
> From: Anthony Dugois <dev.anthonydugois@gmail.com>
> Subject: Hey, I have a project to show you!
> Date: Sun, 14 Jun 2015 00:57:15 +0000
> To: t.wiszniewski@gmail.com
> 
Hello Tomek Wiszniewski! I'm Anthony. I send you this email because I want to tell you about a project called Sinapps (http://sinapps.co) I'm currently developing with 2 friends. I've seen you gave a star to Ghost on GitHub, that's where I got your email address by the way. It was publicly displayed on your profile so I hope you don't mind. I'm emailing you because our project, Sinapps, may interest you, and I would like you to give us a feedback too! :D Sinapps is a social network that creates websites, a new kind of blogging platform. We want to allow people to start a website easily and to reach an audience quickly. The idea is to allow the user to create a website and to publish content on it, the website is connected to our built-in social network, so the websites > and the users can get followed, and the content published on the websites are used to generate timeline on the social network. The social network and the websites hosted on the platform shares the same user base, so it's very easy to bring people such as your followers to contribute to your website, and to get an audience quickly. Sinapps uses Markdown everywhere, just like Ghost does actually. And we use a markdown editor that is very similar to the one they built, except that we added a WYSWYG mode. That would be very cool if you try it out and drop us a feedback. You can do so on the timeline of the #feedback hashtag: http://sinapps.co/hashtag/feedback ! We launched recently so we would be very happy if you do so. :) http://sinapps.co Buh bye!

Looks like a great idea! We might send something similar to those that have starred *ramda*, *101* or *underscore* – once we hit 1.0.

**Comment by tomekwi** [comment]
@stoeffel how about adding #118 and #107 through #116 to the milestone 1.0?

And then linking out [![Stability: unstable](https://img.shields.io/badge/stability-unstable-yellowgreen.svg)](https://nodejs.org/api/documentation.html#documentation_stability_index) to https://github.com/1-liners/1-liners/milestones/1.0.0 instead?

**Comment by stoeffel** [comment]
> Looks like a great idea

:+1: although it sounds a little bit like spamming.

> how about adding #118 and #107 through #116 to the milestone 1.0?
And then linking our Stability: unstable to https://github.com/1-liners/1-liners/milestones/1.0.0 instead?

SGTM :+1:

**Comment by tomekwi** [comment]
>  it sounds a little bit like spamming

Yeah, I thought so at first. But to be honest, if you make your email public on GitHub, it’s a fair deal. When a spam email passes gmail filters, I delete it instantly without looking at it.

But I read this one. I liked the tone it was written in. And I visited the page. I gave no feedback because it turned out to be something I don’t need. But anyway, my mind gradually changed from “span in disguise…” to “I even like these guys.”
