### ISSUE TITLE
separate utils to own repo

### ISSUE THREAD

**Issue by stoeffel** [1-liners/1-liners#72]
- [x] 1-liners/es6-indexer (utils/createIndex.js)
- [ ] use doxie
- [x] 1-liners/get-modules (utils/getModules.js)

**Comment by stoeffel** [comment]
They could be useful in other projects to. we could separate them and create a simple cli for them.

**Comment by tomekwi** [comment]
:+1:

**Comment by stoeffel** [comment]
dox-to-markdown is a better name then create-doc as you suggessted.

**Comment by tomekwi** [comment]
how about *doc-dox*?

**Comment by stoeffel** [comment]
even better

**Comment by tomekwi** [comment]
> 1-liners/doc-dox

As I mentioned in https://github.com/tomekwi/stereo/issues/3#issuecomment-105153008 I’m thinking of creating a generic dox-to-markdown tool. So far I’ve only created a repo: [tomekwi/doxie](https://github.com/tomekwi/doxie).

I think it’ll be generic enough to cover our use-case, plus group the functions by category (array, string, operators etc.). Think:

```
$ dox module/*.js | doxie \
  --sort-by module \
  --group-by category build/category-template.js \
  --template build/docs-template.js \
  --inject-into documentation/README.md
```

The only thing is, I don’t know when I’ll be able to code it. If I get the green light at my office, I could even start on Wednesday. Otherwise it’ll have to wait :(

**Comment by stoeffel** [comment]
:+1:  for doxie.
I will try to get some time to help you with that.

**Comment by tomekwi** [comment]
Thanks a lot! :)

I’ll let you know tomorrow how things are. I already have a bunch of ideas :)

**Comment by hemanth** [comment]
:+1:

**Comment by tomekwi** [comment]
Yeah! Got the green light :) I’ll probably start tomorrow.

It’ll be on company time – so I can invest lots of time, but there are a couple of drawbacks. For one, I’ll have to transfer the repo. For two, I can’t add you as a collaborator :( Are you OK with that @stoeffel?

**Comment by tomekwi** [comment]
@stoeffel you can get an idea how I see this here: https://github.com/studio-b12/doxie-core
